# Generated by Django 4.1.1 on 2023-08-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cost', models.CharField(default='', max_length=5)),
                ('max', models.CharField(default='', max_length=5)),
                ('faction', models.CharField(default='', max_length=15)),
                ('isEquipment', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cycle', models.CharField(default='None', max_length=30)),
                ('cost', models.CharField(default='0', max_length=5)),
                ('max', models.CharField(blank=True, default='1', max_length=5)),
                ('faction', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KiFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=5)),
                ('timing', models.CharField(choices=[('Active', 'Active'), ('Instant', 'Instant'), ('Simple', 'Simple'), ('Complex', 'Complex')], default='A', max_length=8)),
                ('featType', models.CharField(choices=[('Pe', 'Personal'), ('Ta', 'Target'), ('Pu', 'Pulse'), ('Au', 'Aura'), ('Sp', 'Special')], default='Pe', max_length=8)),
                ('featRange', models.CharField(blank=True, default='', max_length=5)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('privacy', models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private')], default='Public', max_length=8)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('exceptional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('cycle', models.CharField(default='None', max_length=30)),
                ('faction', models.CharField(default='', max_length=15)),
                ('validation', models.CharField(default='Unit.objects.all()', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('full', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meleePool', models.CharField(default='0', max_length=3)),
                ('meleeBoost', models.CharField(blank=True, default='0', max_length=3)),
                ('rangedPool', models.CharField(default='0', max_length=3)),
                ('rangedBoost', models.CharField(blank=True, default='0', max_length=3)),
                ('movePool', models.CharField(default='0', max_length=3)),
                ('moveBoost', models.CharField(blank=True, default='0', max_length=3)),
                ('kiStat', models.CharField(default='0', max_length=3)),
                ('kiBoost', models.CharField(blank=True, default='0', max_length=3)),
                ('kiMax', models.CharField(default='0', max_length=3)),
                ('wounds', models.CharField(blank=True, default='5', max_length=3)),
                ('size', models.CharField(default='Small', max_length=10)),
                ('baseSize', models.CharField(default='30', max_length=3)),
                ('cost', models.CharField(default='0', max_length=10)),
                ('faction', models.CharField(default='ronin', max_length=15)),
                ('uniqueEffects', models.CharField(blank=True, default='', max_length=500)),
                ('kiFeats', models.ManyToManyField(to='bushido.kifeat')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('strength', models.CharField(default='+0', max_length=5)),
                ('isRanged', models.BooleanField(default=False)),
                ('shortRange', models.CharField(blank=True, default='', max_length=5)),
                ('mediumRange', models.CharField(blank=True, default='', max_length=5)),
                ('longRange', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(blank=True, default='0', max_length=3)),
                ('Y', models.CharField(blank=True, default='0', max_length=3)),
                ('descriptor', models.CharField(blank=True, default='', max_length=20)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.trait')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(default='0', max_length=3)),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.special')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='specials',
            field=models.ManyToManyField(blank=True, through='bushido.WeaponSpecial', to='bushido.special'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='traits',
            field=models.ManyToManyField(blank=True, through='bushido.WeaponTrait', to='bushido.trait'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useUnofficialCards', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='bushido.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(blank=True, default='0', max_length=3)),
                ('Y', models.CharField(blank=True, default='0', max_length=3)),
                ('descriptor', models.CharField(blank=True, default='', max_length=20)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.trait')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='traits',
            field=models.ManyToManyField(through='bushido.UnitTrait', to='bushido.trait'),
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=30)),
                ('enhancements', models.ManyToManyField(blank=True, to='bushido.enhancement')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.list')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bushido.theme'),
        ),
        migrations.AddField(
            model_name='list',
            name='units',
            field=models.ManyToManyField(through='bushido.ListUnit', to='bushido.unit'),
        ),
    ]
