# Generated by Django 4.1.1 on 2022-10-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KiFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('timing', models.CharField(choices=[('A', 'Active'), ('I', 'Instant'), ('S', 'Simple'), ('C', 'Complex')], default='A', max_length=8)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meleePool', models.IntegerField(default=0)),
                ('rangedPool', models.IntegerField(default=0)),
                ('movePool', models.IntegerField(default=0)),
                ('kiStat', models.IntegerField(default=0)),
                ('kiMax', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnitFeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.kifeat')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
    ]
