# Generated by Django 4.1.1 on 2022-10-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitFeats',
            new_name='UnitFeat',
        ),
    ]
