# Generated by Django 4.1.1 on 2022-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0002_rename_unitfeats_unitfeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kifeat',
            name='type',
            field=models.CharField(choices=[('Pe', 'Personal'), ('Ta', 'Target'), ('Pu', 'Pulse'), ('Au', 'Aura'), ('Sp', 'Special')], default='Pe', max_length=8),
        ),
    ]
