# Generated by Django 4.1.1 on 2022-10-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0003_kifeat_type'),
    ]

    operations = [
    ]
