# Generated by Django 4.1.1 on 2022-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0004_auto_20221005_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kifeat',
            name='cost',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kiMax',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kiStat',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='meleePool',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='movePool',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rangedPool',
            field=models.CharField(max_length=3),
        ),
    ]
