# Generated by Django 4.1.1 on 2022-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0006_unit_kiboost_unit_meleeboost_unit_moveboost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='faction',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
