# Generated by Django 4.1.1 on 2022-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0007_unit_cost_unit_faction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kifeat',
            old_name='type',
            new_name='featType',
        ),
        migrations.AddField(
            model_name='kifeat',
            name='featRange',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='kifeat',
            name='cost',
            field=models.CharField(max_length=5),
        ),
    ]
