# Generated by Django 4.1.1 on 2022-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0008_rename_type_kifeat_feattype_kifeat_featrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kifeat',
            name='timing',
            field=models.CharField(choices=[('Active', 'A'), ('Instant', 'I'), ('Simple', 'S'), ('Complex', 'C')], default='A', max_length=8),
        ),
    ]
