# Generated by Django 4.1.1 on 2022-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0010_alter_kifeat_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='kiFeats',
            field=models.ManyToManyField(to='bushido.kifeat'),
        ),
    ]
