# Generated by Django 4.1.1 on 2023-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0013_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cost', models.CharField(default='', max_length=5)),
                ('max', models.CharField(default='', max_length=5)),
                ('faction', models.CharField(default='', max_length=15)),
                ('isEquipment', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('cycle', models.CharField(default='None', max_length=30)),
                ('cost', models.CharField(default='0', max_length=5)),
                ('max', models.CharField(default='1', max_length=5)),
                ('faction', models.CharField(default='', max_length=15)),
                ('description', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private')], default='Public', max_length=8),
        ),
    ]
