# Generated by Django 4.1.1 on 2023-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0014_enhancement_event_list_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('cycle', models.CharField(default='None', max_length=30)),
                ('faction', models.CharField(default='', max_length=15)),
                ('validation', models.CharField(default='Unit.objects.all()', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
