# Generated by Django 4.1.1 on 2023-05-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0015_theme_alter_enhancement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='trait',
            name='full',
            field=models.CharField(default=models.CharField(max_length=20), max_length=30),
        ),
    ]
