# Generated by Django 4.1.1 on 2023-05-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0016_faction_trait_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='full',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
