# Generated by Django 4.1.1 on 2023-05-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0017_alter_trait_full_alter_trait_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max',
            field=models.CharField(blank=True, default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kiBoost',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='meleeBoost',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='moveBoost',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rangedBoost',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='wounds',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unittrait',
            name='X',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unittrait',
            name='Y',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='unittrait',
            name='descriptor',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
