# Generated by Django 4.1.1 on 2023-05-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0018_alter_event_max_alter_unit_kiboost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
    ]
