# Generated by Django 4.1.1 on 2023-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0019_unittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='validation',
            field=models.CharField(default='Unit.objects.all()', max_length=500),
        ),
    ]
