# Generated by Django 4.1.1 on 2023-05-31 16:55

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0020_alter_theme_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='theme',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bushido.theme'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='list',
            name='units',
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False)),
                ('equipment', models.CharField(max_length=30)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.list')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='units',
            field=models.ManyToManyField(through='bushido.ListUnit', to='bushido.unit'),
        ),
    ]
