# Generated by Django 4.1.1 on 2023-05-31 17:15

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0022_alter_list_id_alter_listunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.UUIDField(default=shortuuid.main.ShortUUID.uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
