# Generated by Django 4.1.1 on 2023-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0023_alter_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='theme',
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
