# Generated by Django 4.1.1 on 2023-05-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0024_remove_list_theme_alter_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='units',
        ),
        migrations.DeleteModel(
            name='ListUnit',
        ),
    ]
