# Generated by Django 4.1.1 on 2023-05-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0025_remove_list_units_delete_listunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
