# Generated by Django 4.1.1 on 2023-05-31 17:53

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('bushido', '0031_list_owner_alter_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private')], default='Public', max_length=8),
        ),
        migrations.AddField(
            model_name='list',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bushido.theme'),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=30)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.list')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bushido.unit')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='units',
            field=models.ManyToManyField(through='bushido.ListUnit', to='bushido.unit'),
        ),
    ]
